Repository UBC-MDS/bccovideda, pull requests merged in 2022-01, with the labels that each got.

#21 Rearranged the functions and modified the docstrings
  src/bccovideda/bccovideda.py
Labels: enhancement

#22 minor modification on spacing of docstring
  src/bccovideda/bccovideda.py
Labels: documentation

#32 Code and unit checks for plotLineByDate function
  src/bccovideda/bccovideda.py
Labels: enhancement

#40 Feat plot hist by cond
  src/bccovideda/plot_hist_by_cond.py
  tests/test_plot_hist_by_cond.py
Labels: enhancement

#46 Final modification before Milestone2 (edited README and modified func…
  README.html
  README.md
  src/bccovideda/plot_hist_by_cond.py
  src/bccovideda/plot_line_by_date.py
Labels: documentation

#60 Fix: Added doc badge to read me
  README.md
Labels: documentation

#62 Addition: Add rep and doc to toml file
  pyproject.toml
Labels: documentation

#64 Enhance: Add plots to readme file
  README.md
  img/data.png
  img/plot_histogram.png
  img/plot_line.png
  img/summary.png
Labels: documentation

#65 Bug: Fix the plots sizes in readme
  README.md
Labels: bug
